
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .


FROM node:20-alpine
WORKDIR /app

# Copy only necessary files from builder
COPY --from=builder /app /app

EXPOSE 7000
CMD ["node", "server.js"]
